// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaAw7Itk4aJE7SkGfGEntBkmbcdTqJLgc',
    appId: '1:905671484134:web:3bc665dbc155b5a6311127',
    messagingSenderId: '905671484134',
    projectId: 'jobreadyyy',
    authDomain: 'jobreadyyy.firebaseapp.com',
    storageBucket: 'jobreadyyy.firebasestorage.app',
    measurementId: 'G-K9887VLZE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD81sf3au9e0gsGrX_Lo0Yzfgr7QXmfKO8',
    appId: '1:905671484134:android:02e1922910dddad4311127',
    messagingSenderId: '905671484134',
    projectId: 'jobreadyyy',
    storageBucket: 'jobreadyyy.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaAw7Itk4aJE7SkGfGEntBkmbcdTqJLgc',
    appId: '1:905671484134:web:9086abd23d64f0ef311127',
    messagingSenderId: '905671484134',
    projectId: 'jobreadyyy',
    authDomain: 'jobreadyyy.firebaseapp.com',
    storageBucket: 'jobreadyyy.firebasestorage.app',
    measurementId: 'G-6510YKYZ3B',
  );

}